version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kyc_postgres
    restart: always
    environment:
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: kyc_pass
      POSTGRES_DB: kyc_db
    ports:
      - "5432:5432"
    volumes:
      - ./kyc-db/pgdata:/var/lib/postgresql/data
